<?php

declare(strict_types=1);
/**
 * NOTICE OF LICENSE.
 *
 * UNIT3D Community Edition is open-sourced software licensed under the GNU Affero General Public License v3.0
 * The details is bundled with this project in the file LICENSE.txt.
 *
 * @project    UNIT3D Community Edition
 *
 * @author     HDVinnie <hdinnovations@protonmail.com>
 * @license    https://www.gnu.org/licenses/agpl-3.0.en.html/ GNU Affero General Public License v3.0
 */

return [
    /*
    |--------------------------------------------------------------------------
    | Default authentication language lines
    |--------------------------------------------------------------------------
    */
    'activation-error'        => 'Banned or invalid token or account already confirmed!',
    'activation-success'      => 'Account confirmed! You may now login!',
    'add-image'               => 'Add another image link',
    'add-profile'             => 'Add another profile link',
    'allow-invite-appl'       => 'Open registration is closed! Must be invited to register! However application signups are open. You have been redirected to the application page!',
    'allow-invite'            => 'Open registration is closed! You must be invited to register! You have been redirected to login page!',
    'are-you'                 => 'Are you:',
    'application'             => 'Application',
    'apply'                   => 'Apply',
    'appl-closed'             => 'Applications are closed',
    'appl-intro'              => 'is a closed community. You must have an invitation link to register. If you cannot get an invitation you may fill out the following application for membership.',
    'appl-reason'             => 'How did you hear about ":sitename" and why do you want in? ',
    'application-submitted'   => 'Your application has been submitted. You will receive a email soon!',
    'banned'                  => 'This account is banned!',
    'check-later'             => 'Check back later!',
    'code'                    => 'TOTP code',
    'confirm-password'        => 'Confirm password',
    'confirm-new-password'    => 'Confirm new password',
    'delete-image'            => 'Delete last image link',
    'delete-profile'          => 'Delete last profile link',
    'email'                   => 'E-mail',
    'email-verification-link' => 'An email verification link has been emailed to you!',
    'enter-recovery'          => 'Please enter one of the recovery codes provided to you when first enabling two-factor authentication.',
    'enter-totp'              => 'Please enter the 6-digit authentication code generated by your app.',
    'failed'                  => 'These credentials do not match our records.',
    'invalid-key'             => 'Invalid or expired invite key!',
    'login'                   => 'Login',
    'login-now-on'            => 'Login now on',
    'logout'                  => 'Logout',
    'lost-password'           => 'Forgot your password?',
    'lost-username'           => 'Forgot your username?',
    'need-invite'             => 'Open registration is disabled and you will need a invite to gain access!',
    'new-password'            => 'New password',
    'newbie'                  => 'New to the game',
    'not-a-member'            => 'Not yet a member ? Signup in less than 30s.',
    'not-activated'           => 'This account has not been activated and is still in validating group. Please check your email for activation link. If you did not receive the activation code, please click "forgot password" and complete the steps.',
    'password'                => 'Password',
    'password-confirm-desc'   => 'Please confirm your password before proceeding.',
    'password-confirmation'   => 'Password confirmation',
    'password-reset'          => 'Reset password',
    'proof-image'             => 'Link to screenshot of profile page',
    'proof-image-title'       => 'Links to profile screenshots',
    'proof-profile'           => 'Link to profile page',
    'proof-profile-title'     => 'Links to your profiles',
    'proof-min'               => '(minimum 2, recommended 3)',
    'recover-my-password'     => 'Recover my password',
    'recovery-code'           => 'Recovery code',
    'register-thanks'         => 'Thanks for signing up! Please check your email to validate your account',
    'remember-me'             => 'Remember me',
    'require-rules'           => 'Please read and accept our rules by scrolling to bottom of page.',
    'send-verification-email' => 'Send verification email',
    'signup'                  => 'Sign up',
    'throttle'                => 'Too many login attempts. Please try again in :seconds seconds.',
    'totp-code'               => 'TOTP code',
    'unlock'                  => 'Unlock',
    'user-icon'               => 'User icon',
    'username'                => 'Username',
    'two-factor-confirm-desc' => 'Please confirm your two factor code before proceeding.',
    'two-factor-confirmation' => 'Two factor confirmation',
    'verify'                  => 'Verify',
    'verify-email'            => 'Verify email',
    'verifying'               => 'Verifying...',
    'veteran'                 => 'Experienced with private trackers',
    'welcome'                 => 'Welcome back!',
    'welcome-restore'         => 'Welcome back! Your account is no longer disabled!',
];
